### ISSUE TITLE
Why I can't pass the second step "Creating the indexes in oqa-solr/"？

### ISSUE THREAD

**Issue by cdzhan** [afader/oqa#4]
I am struck on following command: ./src/main/scripts/create-indexes-small.sh.
It's showing me some error as following:
<------------------------------------------------------------------------------
[cdzhan@Linux1 oqa-solr]$ ./src/main/scripts/start-all.sh
Process forked, pid: 20188
Process forked, pid: 20216
Process forked, pid: 20249
[cdzhan@Linux1 oqa-solr]$ ./src/main/scripts/create-indexes-small.sh
Indexing paraphrase data...
Traceback (most recent call last):
  File "/home/cdzhan/qald/oqa-master/oqa-solr/src/main/scripts/index.py", line 14, in <module>
    utils.index_objects(objects, host, port, collection)
  File "/home/cdzhan/qald/oqa-master/oqa-solr/src/main/scripts/utils.py", line 18, in index_objects
    urllib2.urlopen(req, encoded)
  File "/usr/local/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/local/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(_args)
  File "/usr/local/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(_args)
  File "/usr/local/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 503: Service Unavailable
Indexing relsyn data...
Traceback (most recent call last):
  File "/home/cdzhan/qald/oqa-master/oqa-solr/src/main/scripts/index-relsyn.py", line 13, in <module>
    utils.index_stream(add_id(sys.stdin), port=port, coll=coll)
  File "/home/cdzhan/qald/oqa-master/oqa-solr/src/main/scripts/utils.py", line 28, in index_stream
    grouped = [x for x in grouped if x != None]
UnboundLocalError: local variable 'grouped' referenced before assignment
<-------------------------------------------------------------------------------------------------
I guess the problem may be the disconnection between the service and my oqa system,
but I can't find the solution.

Please guide me ...

**Comment by NoobFang** [comment]
1. The HTTP Error 503 might be caused by the port occupation. If the "start-all.sh" has been executed, when you want to restart them, you should kill the processes manually instead of using "stop-all.sh" simply.
2. The line 28 and 29 of "utils.py" might be exchanged to fix this. But I'm not sure whether any subsequent bugs could be brought by my modification. @afader 

It works when I tried to build this OQA system.

**Comment by cdzhan** [comment]
Now it works, thanks for your help!

**Comment by afader** [comment]
Thanks, @fhy-zju!
